variavel = input('Digite algo no seu teclado.')
print(f'A Variavel escolhida foi: {variavel}')
print(variavel, 'É do tipo primitivo'), print(type(variavel))
print(f'A variavel "{variavel} " é alfabética, verdadeiro ou falso?'), print(variavel.isalpha())
print(f'A variavel "{variavel} " é alfanumérica, verdadeiro ou falso?'), print(variavel.isalnum())
print(f'A variavel "{variavel} " é 7-bit US-ASCII, verdadeiro ou falso?'), print(variavel.isascii())
print(f'A variavel "{variavel} " é numérica, verdadeiro ou falso?'), print(variavel.isdigit())
print(f'A variavel "{variavel} " é minuscula, verdadeiro ou falso?'), print(variavel.islower())
print(f'A variavel "{variavel} " é maiuscula, verdadeiro ou falso?'), print(variavel.isupper())
print(f'A variavel "{variavel} " é decimal, verdadeiro ou falso?'), print(variavel.isdecimal())
print(f'A variavel "{variavel} " é um identificador valido, verdadeiro ou falso?'), print(variavel.isidentifier())
print(f'A variavel "{variavel} " é numérica, verdadeiro ou falso?'), print(variavel.isnumeric())
print(f'A variavel "{variavel} " é printavel em tela, verdadeiro ou falso?'), print(variavel.isprintable())
print(f'A variavel "{variavel} " é somente espaços, verdadeiro ou falso?'), print(variavel.isspace())
print(f'A variavel "{variavel} " está capitalizada, verdadeiro ou falso?'), print(variavel.istitle())
